### ISSUE TITLE
Potential EULA violation

### ISSUE THREAD

**Issue by fontpolice** [arjunkapoor/1-page-coding-challenge#2]
Dear arjunkapoor,

It has come to our attention through [FontFinder](http://www.fontfinder.io) that your hosting of ProximaNova-Black.otf in this _public_ repository could be a potential violation of the End User License Agreement (EULA) between yourself and the respective foundry.

We recommend that you [remove](https://github.com/blog/1545-deleting-files-on-github) the files to avoid further action.

Sincerely,
The Font Police

**Comment by arjunkapoor** [comment]
Removed. I wasn't made aware of that in the first place when I was provided with the fonts from the foundry.

**Comment by fontpolice** [comment]
Thank you for your cooperation.
